name: movies
description: A new Flutter package project.
publish_to: 'none'
version: 0.0.1
homepage: null

environment:
  sdk: '>=2.18.5 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  cached_network_image: ^3.3.0
  core:
    path: ../core
  dartz: ^0.10.1
  equatable: ^2.0.5
  firebase_crashlytics: ^3.4.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_rating_bar: ^4.0.1
  rxdart: ^0.27.7

dev_dependencies:
  bloc_test: ^9.1.5
  build_runner: ^2.4.6
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  mockito: ^5.4.3
  mocktail: ^1.0.1

flutter: null
